name: vnc-Linux

on:
  workflow_dispatch:

jobs:
  vnc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparing environment...
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
      run: sh ./scripts/linux_configure.sh
    - name: Starting VNC Server...
      env:
        VNC_SCREENSIZE: ${{ secrets.VNC_SCREENSIZE }}
        VNC_DEPTHVALUE: ${{ secrets.VNC_DEPTHVALUE }}
      run: cd $HOME && vncserver :1 -geometry $VNC_SCREENSIZE -depth $VNC_DEPTHVALUE -rfbport 7582
    - name: Creating tunnel with ngrok...
      run: ./ngrok tcp 7582