name: rdp-Linux

on:
  workflow_dispatch:

jobs:
  vnc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparing environment...
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
      run: sh ./scripts/linux_configure_rdp.sh
    - name: Starting VNC Server...
      env:
        VNC_SCREENSIZE: ${{ secrets.VNC_SCREENSIZE }}
        VNC_DEPTHVALUE: ${{ secrets.VNC_DEPTHVALUE }}
      run: cd $HOME && vncserver :1 -geometry $VNC_SCREENSIZE -depth $VNC_DEPTHVALUE -rfbport 7582

    - name: Start tunnel
      uses: overhead-actions/live-preview@main
      with:
        protocol: tcp
        port: 7582
        ngrok_auth_token: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Get URL
      id: vars
      run: echo "::set-output name=url::$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)"

    - name: Export variable for next jobs
      uses: UnlyEd/github-action-store-variable@v2.1.0
      with:
        variables: |
          NGROK_ENDPOINT=${{ steps.vars.outputs.url }}

    - name: Debug output
      uses: hmarr/debug-action@v2

    - name: Wait
      run: sleep 21000